### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by maxarvid** [gsim1903/weatherapp2-#1]
Hi Gavin, looks like the `package.json` is missing a dependency or two:
![image](https://user-images.githubusercontent.com/31871856/149737479-49406b9a-f74d-4b10-819a-3872983191bd.png)

**Comment by gsim1903** [comment]
I've added semantic, node-env though the problem still seems to exist. Are there another others to add?
<img width="947" alt="Screenshot 2022-01-18 at 08 44 51" src="https://user-images.githubusercontent.com/92160782/149901883-92d63a87-2120-4e06-8c7a-645eed62fb28.png">

**Comment by maxarvid** [comment]
Good stuff. Did you run `yarn` on your machine after adding the dependencies? I did and it runs on my machine now. The stubs are working as intended but it looks like it has trouble displaying the city:
![image](https://user-images.githubusercontent.com/31871856/149904281-d540af01-029c-4844-8e79-518d1ab8008c.png)
